POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2MGZlOTNkMmUyNDE2YjIxNDhhM2NlOGIiLCJpYXQiOjE2MjgyNDU4NzAsImV4cCI6MTYyODI0OTQ3MH0.AWcefAbdc9uVxxu8lE_3hKfXIgxN3nOINAquishr3-c

{
    "author": "Me myself and I",
    "url": "wwww.fullstäckiä.fi/blog"
}